// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5tfN0Mr3YBwuXgHSB1L2pmBilo8WHlxU',
    appId: '1:208412899004:web:18efd05e58a51209d482b9',
    messagingSenderId: '208412899004',
    projectId: 'srkr-ec6c5',
    authDomain: 'srkr-ec6c5.firebaseapp.com',
    databaseURL: 'https://srkr-ec6c5-default-rtdb.firebaseio.com',
    storageBucket: 'srkr-ec6c5.appspot.com',
    measurementId: 'G-94XDFDW615',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd5TGvCYzn8WsmjOymbr-35dEJ4qpG5b0',
    appId: '1:208412899004:android:37d7902b0468b9f0d482b9',
    messagingSenderId: '208412899004',
    projectId: 'srkr-ec6c5',
    databaseURL: 'https://srkr-ec6c5-default-rtdb.firebaseio.com',
    storageBucket: 'srkr-ec6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMo63HbPRZMN9zoz4cSCY_fMfWuOkvMow',
    appId: '1:208412899004:ios:2e1453f683871f22d482b9',
    messagingSenderId: '208412899004',
    projectId: 'srkr-ec6c5',
    databaseURL: 'https://srkr-ec6c5-default-rtdb.firebaseio.com',
    storageBucket: 'srkr-ec6c5.appspot.com',
    androidClientId: '208412899004-ic3qrao8gbgrerpgs5j6d638id27li7a.apps.googleusercontent.com',
    iosClientId: '208412899004-3ku4j7aqfgod7l1bmg1hk9uq5a3p51cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.srkr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMo63HbPRZMN9zoz4cSCY_fMfWuOkvMow',
    appId: '1:208412899004:ios:387675effb173adfd482b9',
    messagingSenderId: '208412899004',
    projectId: 'srkr-ec6c5',
    databaseURL: 'https://srkr-ec6c5-default-rtdb.firebaseio.com',
    storageBucket: 'srkr-ec6c5.appspot.com',
    androidClientId: '208412899004-ic3qrao8gbgrerpgs5j6d638id27li7a.apps.googleusercontent.com',
    iosClientId: '208412899004-odbhnurp145vb22805r7mgg7jsfoim50.apps.googleusercontent.com',
    iosBundleId: 'com.example.srkr.RunnerTests',
  );
}
